//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCP_Nalashaa_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commuter
    {
        public int CommuterId { get; set; }
        public Nullable<int> TripId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Trip Trip { get; set; }
        public virtual User User { get; set; }
    }
}
