//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCP_Nalashaa_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int TripId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public Nullable<double> Origin_Lat { get; set; }
        public Nullable<double> Origin_Ln { get; set; }
        public Nullable<double> Destination_Lat { get; set; }
        public Nullable<double> Destination_Ln { get; set; }
        public Nullable<int> CommutersCapacity { get; set; }
        public Nullable<System.DateTime> TripDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> TripStatus { get; set; }
    }
}
