//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCP_Nalashaa_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripStatusMaster
    {
        public TripStatusMaster()
        {
            this.Trips = new HashSet<Trip>();
        }
    
        public int TripStatusId { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
