//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCP_Nalashaa_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Commuters = new HashSet<Commuter>();
            this.CommuterRequests = new HashSet<CommuterRequest>();
            this.Trips = new HashSet<Trip>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string UserPassword { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
    
        public virtual ICollection<Commuter> Commuters { get; set; }
        public virtual ICollection<CommuterRequest> CommuterRequests { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
